[package]
name = "semantic-exit"
version = "1.0.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
thiserror = "1.0.38"

[dev-dependencies]
libc = "0.2"
regex = "1.7.0"
test-case = "2.2.2"
