on: push

name: CI
jobs:
  go:
    name: Test (Go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go test -v

  rust:
    name: Test (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: bin/cargo test --all-features --all-targets --locked
